#!/usr/bin/env cwl-runner

cwlVersion: v1.0
class: CommandLineTool

requirements:
  - class: InlineJavascriptRequirement

hints:
  - class: DockerRequirement
    dockerPull: ACCOUNT/calling_utils:VERSION

baseCommand: [merge_callers_v2.py]

inputs:
  - id: input_files_TNhaplotyper2_vcf_gz
    type:
      -
        items: File
        type: array
        inputBinding:
          prefix: -i
          position: 1
          valueFrom: $( "TNhaplotyper2:" + self.path )
    secondaryFiles:
      - .tbi
    doc: List of input VCF files generated by TNhaplotyper2. Compressed with the corresponding index file

  - id: input_files_core_ids_TNhaplotyper2
    type:
      -
        items: string
        type: array
        inputBinding:
          prefix: -c
          position: 2
          valueFrom: $( "TNhaplotyper2:" + self )
    doc: Core identifiers for VCF files generated by TNhaplotyper2 (1:1 match) 

  - id: input_files_Strelka2_vcf_gz
    type:
      -
        items: File
        type: array
        inputBinding:
          prefix: -i
          position: 3
          valueFrom: $( "Strelka2:" + self.path )
    secondaryFiles:
      - .tbi
    doc: List of input VCF files generated by Strelka2. Compressed with the corresponding index file

  - id: input_files_core_ids_Strelka2
    type:
      -
        items: string
        type: array
        inputBinding:
          prefix: -c
          position: 4
          valueFrom: $( "Strelka2:" + self )
    doc: Core identifiers for VCF files generated by Strelka2 (1:1 match) (eg. 002B1 002B3 002B1-002B3...)

  - id: input_files_longcallD_vcf_gz
    type:
      -
        items: File
        type: array
        inputBinding:
          prefix: -i
          position: 5
          valueFrom: $( "longcallD:" + self.path )
    default: []
    secondaryFiles:
      - .tbi
    doc: List of input VCF files generated by longcallD. Compressed with the corresponding index file

  - id: input_files_core_ids_longcallD
    type:
      -
        items: string
        type: array
        inputBinding:
          prefix: -c
          position: 6
          valueFrom: $( "longcallD:" + self )
    default: []
    doc: Core identifiers for VCF files generated by longcallD (1:1 match) (eg. 001A2 001B2 001A2-001B2...)

  - id: input_files_RUFUS_vcf_gz
    type:
      -
        items: File
        type: array
        inputBinding:
          prefix: -i
          position: 7
          valueFrom: $( "RUFUS:" + self.path )
    secondaryFiles:
      - .tbi
    doc: List of input VCF files generated by RUFUS. Compressed with the corresponding index file

  - id: input_files_core_ids_RUFUS
    type:
      -
        items: string
        type: array
        inputBinding:
          prefix: -c
          position: 8
          valueFrom: $( "RUFUS:" + self )
    doc: Core identifiers for VCF files generated by RUFUS (1:1 match) (eg. 002B1 002B3 002B1-002B3...)

  - id: sample_name
    type: string
    inputBinding:
      prefix: -s
    doc: Name of the sample. This will be added to the merged VCF header

  - id: output_file_name
    type: string
    default: "merged.vcf.gz"
    inputBinding:
      prefix: -o
    doc: Output file name

outputs:
  - id: output_file_vcf_gz
    type: File
    outputBinding:
      glob: $(inputs.output_file_name)
    secondaryFiles:
      - .tbi
    doc: Compressed VCF with index

doc: |
  Merges variant calls from multiple callers into a single VCF file. |
  Supports TNhaplotyper2, Strelka2, longcallD, and RUFUS callers. |
  v2 supports core-specific and merged calling VCF files.
